pim_api_product_get:
    path: /variant-groups/{code}
    defaults: { _controller: pim_api.controller.variant_group:getAction, _format: json }
    methods: [GET]

pim_api_variant_group_create:
    path: /variant-groups
    defaults: { _controller: pim_api.controller.variant_group:createAction, _format: json }
    methods: [POST]
